name: test
on: [push, pull_request]

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: test
      env:
        GO111MODULE: on
        GOPATH: /home/runner/work/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go test ./...
